version: '3.8'

services:
  nginx-custom:
    build: .
    image: my-custom-nginx-image
    container_name: nginx-compose-version
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./config/html:/usr/share/nginx/html
      - ./config/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/conf/.htpasswd:/etc/nginx/.htpasswd
      - ./config/certs:/etc/ssl/certs
    restart: unless-stopped
